"""initial migration

Revision ID: a9e54c9ec9af
Revises: 
Create Date: 2018-10-16 10:23:29.261479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e54c9ec9af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('optionid', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bedinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('areaid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['areaid'], ['inhospitalarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkitemname', sa.String(length=64), nullable=True),
    sa.Column('itemclass', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemclass'], ['checkclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctorcycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctorid', sa.String(length=64), nullable=True),
    sa.Column('classid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['classid'], ['hospitalclass.id'], ),
    sa.ForeignKeyConstraint(['doctorid'], ['doctorinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examitemname', sa.String(length=64), nullable=True),
    sa.Column('itemclass', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemclass'], ['checkclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expertstimetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctorinfoid', sa.String(length=64), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['hospitalclass.id'], ),
    sa.ForeignKeyConstraint(['doctorinfoid'], ['doctorinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inpatienttimetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctorinfoid', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['doctorinfoid'], ['doctorinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outpatienttimetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctorcycleid', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['doctorcycleid'], ['doctorcycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outpatienttimetable')
    op.drop_table('inpatienttimetable')
    op.drop_table('expertstimetable')
    op.drop_table('examitem')
    op.drop_table('doctorcycle')
    op.drop_table('checkitem')
    op.drop_table('bedinfo')
    op.drop_table('price')
    # ### end Alembic commands ###
